// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxbrfmjxrfhntjkdlcbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4YnJmbWp4cmZobnRqa2RsY2J6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NzAzNTksImV4cCI6MjA2OTE0NjM1OX0.ie9jOgpXRcxS35K1JGkXxY88ymhtQWWIdEWJRzl6l-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});